// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed shopcategories.yaml
var resourceShopcategoriesYamlData []byte
var resourceShopcategoriesYaml = &fyne.StaticResource{
	StaticName:    "shopcategories.yaml",
	StaticContent: resourceShopcategoriesYamlData,
}
